import test from 'node:test';import assert from 'node:assert/strict';import {request as rawRequest} from 'node:http';
import {createApp,readConfig} from '../dist/server/app.js';
async function app(config=readConfig({},process.cwd()),transport){const server=createApp(config,transport);await new Promise(r=>server.listen(0,'127.0.0.1',r));const url='http://127.0.0.1:'+server.address().port;const cfg=await (await fetch(url+'/api/config')).json();return {server,url,cfg,close:()=>new Promise(r=>server.close(r))};}
const body=text=>({provider:'mock',consent:false,fault:'none',messages:[{role:'user',content:text}],state:{ui_state:'',client_events:[]}});
const post=(a,data,extra={})=>fetch(a.url+'/api/turn',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':a.cfg.token,...extra},body:JSON.stringify(data)});
test('HTTP protects static files, origin and local token; model modes remain off',async()=>{const a=await app();try{assert.equal(a.cfg.defaultProvider,'mock');assert.equal(a.cfg.key,undefined);for(const path of ['/src/server/cli.ts','/.env','/skills/workout.md'])assert.equal((await fetch(a.url+path)).status,404);assert.equal((await post(a,body('/demo'),{'X-Local-Token':'wrong'})).status,403);assert.equal((await post(a,body('/demo'),{Origin:'https://example.org'})).status,403);const status=await new Promise(resolve=>rawRequest(a.url,{headers:{Host:'evil.example'}},r=>{r.resume();resolve(r.statusCode);}).end());assert.equal(status,403);assert.equal((await post(a,{...body('/demo'),provider:'claude-cli',consent:true})).status,403);assert.equal((await post(a,{...body('/demo'),provider:'codex-cli',consent:true})).status,503);}finally{await a.close();}});
test('HTTP mock provides protocol/hash metadata and validates faults and input',async()=>{const a=await app();try{const response=await post(a,body('/demo'));assert.equal(response.status,200);const data=await response.json();assert(data.turn.reply.includes('Timer("Sample timer", 10)'));assert.equal(data.versions.app,'2.0.0');assert.equal(data.versions.protocolHash.length,64);for(const fault of ['schema','request'])assert.equal((await post(a,{...body('/demo'),fault})).status,502);assert.equal((await post(a,{...body('x'),extra:true})).status,400);}finally{await a.close();}});
test('HTTP API errors redact raw provider bodies; valid envelope with invalid screen rejected',async()=>{for(const invalid of [false,true]){const config=readConfig({ALLOW_LIVE_API:'true',OPENAI_API_KEY:'fake-private'},process.cwd());const transport=async()=>invalid?new Response(JSON.stringify({status:'completed',output:[{type:'message',content:[{type:'output_text',text:JSON.stringify({reply:'```openui\nroot = Bad()\n```'})}]}]})):new Response('fake-private',{status:500});const a=await app(config,transport);try{const response=await post(a,{...body('hello'),provider:'openai-api',consent:true});assert.equal(response.status,502);assert(!(await response.text()).includes('fake-private'));}finally{await a.close();}}});
test('disconnect aborts provider request',async()=>{let started,aborted;const seen=new Promise(r=>started=r),cancelled=new Promise(r=>aborted=r);const a=await app(readConfig({ALLOW_LIVE_API:'true',OPENAI_API_KEY:'fake'},process.cwd()),(_u,o)=>{started();return new Promise((resolve,reject)=>o.signal.addEventListener('abort',()=>{aborted();reject(new Error('abort'));}));});try{const controller=new AbortController();const task=fetch(a.url+'/api/turn',{method:'POST',headers:{'Content-Type':'application/json','X-Local-Token':a.cfg.token},body:JSON.stringify({...body('hi'),provider:'openai-api',consent:true}),signal:controller.signal}).catch(()=>{});await seen;controller.abort();await task;await Promise.race([cancelled,new Promise((_,reject)=>setTimeout(()=>reject(new Error('abort missing')),1500))]);}finally{await a.close();}});
